### ISSUE TITLE
Return value : UNDEFINED

### ISSUE THREAD

**Issue by ChuaMichelle** [ecwyne/meteor-xmlrpc#1]
Hello,

First of all, I'd like to give thanks for this awesome package ! It's simple and works well. 

I would just love to know if anyone has had any problems regarding the returns value. I get the results properly but my functions return mean undefined value rather than the results. 

I'm wondering what most of you guys do to hack this lil problem, I would really love to know, I tried using Meteor.wrapAsync() and a package called Async.wrap but I just cant seem to make it work, 

Any help would be much appreciated, thank you in advance ! :)

**Comment by ecwyne** [comment]
@ChuaMichelle can you share some sample code which is giving you the issue. I have not had any issues with functions returning `undefined` before.

**Comment by ChuaMichelle** [comment]
Im using another package to call upon an external API. This action takes time, and thus the root of the problem. ( genericFunction doesn't wait for the results and returns an undefined value ) 

``` javascript
// client/templates/file.js
if (Meteor.isClient) {
    'click .newClient': function(e, template) {
        Meteor.call('methodOne', function (err, res) {
            if(err){
                console.log(err);
            } else {
                console.log('response: ', res);
            }
        });

    }
}
```

``` javascript
// server/file.js
function genericFunction(clientURL, methodName, params) {
    var client = new Meteor.XmlRpcClient(clientURL);
    var res;
    client.methodCall(methodName, params, function(err, ress) {
        if(err) console.log(methodName+ " PROD_err : ", err);
        if (ress) {
            console.log(methodName +" PROD_res : ", ress);
            res = ress;
        }
    });
    return res;
}

Meteor.methods({
    methodOne: function() {
        var result = genericFunction("APIURL", "hosting.datacenter.list", ["APIKEY"]);
        return result;
    }
});
```

**Comment by ecwyne** [comment]
Check this out
https://www.discovermeteor.com/patterns/5828399

``` javascript
// server/file.js
function genericFunction(clientURL, methodName, params) {
    var client = new Meteor.XmlRpcClient(clientURL);
    Future = Npm.require('fibers/future');
    var myFuture = new Future();
    client.methodCall(methodName, params, function(err, ress) {
        if(err) console.log(methodName+ " PROD_err : ", err);
        if (ress) {
            console.log(methodName +" PROD_res : ", ress);
           myFuture.return(ress);
        }
    });
    return myFuture.wait();
}
```

**Comment by ChuaMichelle** [comment]
Oh wow, thank you ! 

I've been playing around the fibers and future modules but I couldn't get my head around it. 

This works perfectly. I've been stuck on this for a week, thank you so much !!

**Comment by ecwyne** [comment]
No worries! Trying to return asynchronous results in a Meteor method is a common use case. That's why there's the post from discovermeteor!

**Comment by ChuaMichelle** [comment]
:+1:
